# Generated by Django 3.1.7 on 2021-03-24 12:04

import catApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('bodyColor', models.CharField(choices=[('1', 'white'), ('2', 'black'), ('3', 'brown'), ('4', 'grey'), ('5', 'ginger'), ('6', 'cream'), ('7', 'fawn'), ('8', 'multi-color')], max_length=12)),
                ('gender', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, validators=[catApp.models.validate_owner])),
            ],
        ),
        migrations.CreateModel(
            name='Hunting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateTimeField()),
                ('dateEnd', models.DateTimeField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunters', to='catApp.cat')),
            ],
        ),
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lootType', models.CharField(choices=[('1', 'rat'), ('2', 'mouse'), ('3', 'bird'), ('4', 'fish'), ('5', 'catnip'), ('6', 'meat'), ('7', 'bone'), ('8', 'leftovers')], max_length=10)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_loots', to='catApp.cat')),
                ('hunting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loots', to='catApp.hunting')),
            ],
        ),
    ]
